setting:
  # UDP 会话超时时间（秒）。超过此时间没有数据交换，程序将自动断开连接以释放资源
  session_timeout: 120
  # 系统底层套接字（Socket）缓冲区大小（MB）。在高并发或大带宽联机时，可以设置更大
  socket_buf_size: 4
  # 单次转发的内存缓冲区大小（KB）。最大 64KB
  packet_buffer_size: 64
  # 流量状态打印频率（秒）。设为 0 将完全关闭定时报告，只在退出时显示最终统计
  report_interval: 300

tunnels:
  - host: "game.example.com"
    services:
      - name: "mc"
        remote: 25565
        local: 25565
        proto: "tcp"

      - name: "帕鲁"
        remote: 8211
        local: 8211
        proto: "udp"

      - name: "teamspeak"
        remote: 9987
        local: 9987
        proto: "udp"

  - host: "2001:db8:a0b:1234::100"
    services:
      - name: "ipv6"
        remote: 222
        local: 333
        proto: "udp"

  - host: "192.168.100.1"
    services:
      - name: "ipv4"
        remote: 444
        local: 444
        proto: "tcp"
